### ISSUE TITLE
There is no -v switch

### ISSUE THREAD

**Issue by doggy8088** [aspnet/AspNetCore.Docs.zh-tw#132]
There is no `-v` switch in `Microsoft.dotnet-openapi 3.1.0`.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 653e14ef-227e-a165-0360-2f59259e16c6
* Version Independent ID: e4685d05-e874-76a3-9780-66b864eca6c1
* Content: [使用 OpenAPI 開發 ASP.NET Core 應用程式](https://docs.microsoft.com/zh-tw/aspnet/core/web-api/microsoft.dotnet-openapi?view=aspnetcore-3.1)
* Content Source: [aspnetcore/web-api/Microsoft.dotnet-openapi.md](https://github.com/aspnet/AspNetCore.Docs.zh-tw/blob/live/aspnetcore/web-api/Microsoft.dotnet-openapi.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-webapi**
* GitHub Login: @ryanbrandenburg
* Microsoft Alias: **rybrande**

**Comment by srvbpigh** [comment]
Hello, @doggy8088
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [aspnet/AspNetCore #17865](https://github.com/aspnet/AspNetCore/issues/17865) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @doggy8088, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore/issues/17865. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
